INSERT INTO country (id, name) VALUES (57, 'Aruba');
INSERT INTO country (id, name) VALUES (87, 'Afghanistan');
INSERT INTO country (id, name) VALUES (149, 'Angola');
INSERT INTO country (id, name) VALUES (19, 'Anguilla');
INSERT INTO country (id, name) VALUES (39, 'Åland Islands');
INSERT INTO country (id, name) VALUES (6, 'Albania');
INSERT INTO country (id, name) VALUES (7, 'Andorra');
INSERT INTO country (id, name) VALUES (8, 'United Arab Emirates');
INSERT INTO country (id, name) VALUES (9, 'Argentina');
INSERT INTO country (id, name) VALUES (10, 'Armenia');
INSERT INTO country (id, name) VALUES (11, 'American Samoa');
INSERT INTO country (id, name) VALUES (12, 'Antarctica');
INSERT INTO country (id, name) VALUES (13, 'French Southern Territories');
INSERT INTO country (id, name) VALUES (14, 'Antigua and Barbuda');
INSERT INTO country (id, name) VALUES (15, 'Australia');
INSERT INTO country (id, name) VALUES (16, 'Austria');
INSERT INTO country (id, name) VALUES (17, 'Azerbaijan');
INSERT INTO country (id, name) VALUES (18, 'Burundi');
INSERT INTO country (id, name) VALUES (20, 'Benin');
INSERT INTO country (id, name) VALUES (21, 'Bonaire, Sint Eustatius and Saba');
INSERT INTO country (id, name) VALUES (22, 'Burkina Faso');
INSERT INTO country (id, name) VALUES (23, 'Bangladesh');
INSERT INTO country (id, name) VALUES (24, 'Bulgaria');
INSERT INTO country (id, name) VALUES (25, 'Bahrain');
INSERT INTO country (id, name) VALUES (26, 'Bahamas');
INSERT INTO country (id, name) VALUES (27, 'Bosnia and Herzegovina');
INSERT INTO country (id, name) VALUES (28, 'Saint Barthélemy');
INSERT INTO country (id, name) VALUES (29, 'Belarus');
INSERT INTO country (id, name) VALUES (30, 'Belize');
INSERT INTO country (id, name) VALUES (31, 'Bermuda');
INSERT INTO country (id, name) VALUES (32, 'Bolivia, Plurinational State of');
INSERT INTO country (id, name) VALUES (33, 'Brazil');
INSERT INTO country (id, name) VALUES (34, 'Barbados');
INSERT INTO country (id, name) VALUES (35, 'Brunei Darussalam');
INSERT INTO country (id, name) VALUES (36, 'Bhutan');
INSERT INTO country (id, name) VALUES (37, 'Bouvet Island');
INSERT INTO country (id, name) VALUES (38, 'Botswana');
INSERT INTO country (id, name) VALUES (40, 'Canada');
INSERT INTO country (id, name) VALUES (41, 'Cocos (Keeling) Islands');
INSERT INTO country (id, name) VALUES (42, 'Switzerland');
INSERT INTO country (id, name) VALUES (43, 'Chile');
INSERT INTO country (id, name) VALUES (44, 'China');
INSERT INTO country (id, name) VALUES (45, 'Côte d''Ivoire');
INSERT INTO country (id, name) VALUES (46, 'Cameroon');
INSERT INTO country (id, name) VALUES (47, 'Congo, The Democratic Republic of the');
INSERT INTO country (id, name) VALUES (48, 'Congo');
INSERT INTO country (id, name) VALUES (49, 'Cook Islands');
INSERT INTO country (id, name) VALUES (50, 'Colombia');
INSERT INTO country (id, name) VALUES (51, 'Comoros');
INSERT INTO country (id, name) VALUES (52, 'Cabo Verde');
INSERT INTO country (id, name) VALUES (53, 'Costa Rica');
INSERT INTO country (id, name) VALUES (54, 'Cuba');
INSERT INTO country (id, name) VALUES (55, 'Curaçao');
INSERT INTO country (id, name) VALUES (56, 'Christmas Island');
INSERT INTO country (id, name) VALUES (58, 'Cyprus');
INSERT INTO country (id, name) VALUES (59, 'Czechia');
INSERT INTO country (id, name) VALUES (60, 'Germany');
INSERT INTO country (id, name) VALUES (61, 'Djibouti');
INSERT INTO country (id, name) VALUES (62, 'Dominica');
INSERT INTO country (id, name) VALUES (63, 'Denmark');
INSERT INTO country (id, name) VALUES (64, 'Dominican Republic');
INSERT INTO country (id, name) VALUES (65, 'Algeria');
INSERT INTO country (id, name) VALUES (66, 'Ecuador');
INSERT INTO country (id, name) VALUES (67, 'Egypt');
INSERT INTO country (id, name) VALUES (68, 'Eritrea');
INSERT INTO country (id, name) VALUES (69, 'Western Sahara');
INSERT INTO country (id, name) VALUES (70, 'Spain');
INSERT INTO country (id, name) VALUES (71, 'Estonia');
INSERT INTO country (id, name) VALUES (72, 'Ethiopia');
INSERT INTO country (id, name) VALUES (73, 'Finland');
INSERT INTO country (id, name) VALUES (74, 'Fiji');
INSERT INTO country (id, name) VALUES (75, 'Falkland Islands (Malvinas)');
INSERT INTO country (id, name) VALUES (76, 'France');
INSERT INTO country (id, name) VALUES (77, 'Faroe Islands');
INSERT INTO country (id, name) VALUES (78, 'Micronesia, Federated States of');
INSERT INTO country (id, name) VALUES (79, 'Gabon');
INSERT INTO country (id, name) VALUES (80, 'United Kingdom');
INSERT INTO country (id, name) VALUES (81, 'Georgia');
INSERT INTO country (id, name) VALUES (82, 'Guernsey');
INSERT INTO country (id, name) VALUES (83, 'Ghana');
INSERT INTO country (id, name) VALUES (84, 'Gibraltar');
INSERT INTO country (id, name) VALUES (85, 'Guinea');
INSERT INTO country (id, name) VALUES (86, 'Guadeloupe');
INSERT INTO country (id, name) VALUES (88, 'Guinea-Bissau');
INSERT INTO country (id, name) VALUES (89, 'Equatorial Guinea');
INSERT INTO country (id, name) VALUES (90, 'Greece');
INSERT INTO country (id, name) VALUES (91, 'Grenada');
INSERT INTO country (id, name) VALUES (92, 'Greenland');
INSERT INTO country (id, name) VALUES (93, 'Guatemala');
INSERT INTO country (id, name) VALUES (94, 'French Guiana');
INSERT INTO country (id, name) VALUES (95, 'Guam');
INSERT INTO country (id, name) VALUES (96, 'Guyana');
INSERT INTO country (id, name) VALUES (97, 'Hong Kong');
INSERT INTO country (id, name) VALUES (98, 'Heard Island and McDonald Islands');
INSERT INTO country (id, name) VALUES (99, 'Honduras');
INSERT INTO country (id, name) VALUES (100, 'Croatia');
INSERT INTO country (id, name) VALUES (101, 'Haiti');
INSERT INTO country (id, name) VALUES (102, 'Hungary');
INSERT INTO country (id, name) VALUES (103, 'Indonesia');
INSERT INTO country (id, name) VALUES (104, 'Isle of Man');
INSERT INTO country (id, name) VALUES (105, 'India');
INSERT INTO country (id, name) VALUES (106, 'British Indian Ocean Territory');
INSERT INTO country (id, name) VALUES (107, 'Ireland');
INSERT INTO country (id, name) VALUES (108, 'Iran, Islamic Republic of');
INSERT INTO country (id, name) VALUES (109, 'Iraq');
INSERT INTO country (id, name) VALUES (110, 'Iceland');
INSERT INTO country (id, name) VALUES (111, 'Israel');
INSERT INTO country (id, name) VALUES (112, 'Italy');
INSERT INTO country (id, name) VALUES (113, 'Jamaica');
INSERT INTO country (id, name) VALUES (114, 'Jersey');
INSERT INTO country (id, name) VALUES (115, 'Jordan');
INSERT INTO country (id, name) VALUES (116, 'Japan');
INSERT INTO country (id, name) VALUES (117, 'Kazakhstan');
INSERT INTO country (id, name) VALUES (118, 'Kenya');
INSERT INTO country (id, name) VALUES (119, 'Kyrgyzstan');
INSERT INTO country (id, name) VALUES (120, 'Cambodia');
INSERT INTO country (id, name) VALUES (121, 'Kiribati');
INSERT INTO country (id, name) VALUES (122, 'Saint Kitts and Nevis');
INSERT INTO country (id, name) VALUES (123, 'Korea, Republic of');
INSERT INTO country (id, name) VALUES (124, 'Kuwait');
INSERT INTO country (id, name) VALUES (125, 'Lao People''s Democratic Republic');
INSERT INTO country (id, name) VALUES (126, 'Lebanon');
INSERT INTO country (id, name) VALUES (127, 'Liberia');
INSERT INTO country (id, name) VALUES (128, 'Libya');
INSERT INTO country (id, name) VALUES (129, 'Saint Lucia');
INSERT INTO country (id, name) VALUES (130, 'Liechtenstein');
INSERT INTO country (id, name) VALUES (131, 'Sri Lanka');
INSERT INTO country (id, name) VALUES (132, 'Lesotho');
INSERT INTO country (id, name) VALUES (133, 'Lithuania');
INSERT INTO country (id, name) VALUES (134, 'Luxembourg');
INSERT INTO country (id, name) VALUES (135, 'Latvia');
INSERT INTO country (id, name) VALUES (136, 'Macao');
INSERT INTO country (id, name) VALUES (137, 'Saint Martin (French part)');
INSERT INTO country (id, name) VALUES (138, 'Morocco');
INSERT INTO country (id, name) VALUES (139, 'Monaco');
INSERT INTO country (id, name) VALUES (140, 'Moldova, Republic of');
INSERT INTO country (id, name) VALUES (141, 'Madagascar');
INSERT INTO country (id, name) VALUES (142, 'Maldives');
INSERT INTO country (id, name) VALUES (143, 'Mexico');
INSERT INTO country (id, name) VALUES (144, 'Marshall Islands');
INSERT INTO country (id, name) VALUES (145, 'North Macedonia');
INSERT INTO country (id, name) VALUES (146, 'Mali');
INSERT INTO country (id, name) VALUES (147, 'Malta');
INSERT INTO country (id, name) VALUES (148, 'Myanmar');
INSERT INTO country (id, name) VALUES (150, 'Mongolia');
INSERT INTO country (id, name) VALUES (151, 'Northern Mariana Islands');
INSERT INTO country (id, name) VALUES (152, 'Mozambique');
INSERT INTO country (id, name) VALUES (153, 'Mauritania');
INSERT INTO country (id, name) VALUES (154, 'Montserrat');
INSERT INTO country (id, name) VALUES (155, 'Martinique');
INSERT INTO country (id, name) VALUES (156, 'Mauritius');
INSERT INTO country (id, name) VALUES (157, 'Malawi');
INSERT INTO country (id, name) VALUES (158, 'Malaysia');
INSERT INTO country (id, name) VALUES (159, 'Mayotte');
INSERT INTO country (id, name) VALUES (160, 'Namibia');
INSERT INTO country (id, name) VALUES (161, 'New Caledonia');
INSERT INTO country (id, name) VALUES (162, 'Niger');
INSERT INTO country (id, name) VALUES (163, 'Norfolk Island');
INSERT INTO country (id, name) VALUES (164, 'Nigeria');
INSERT INTO country (id, name) VALUES (165, 'Nicaragua');
INSERT INTO country (id, name) VALUES (166, 'Niue');
INSERT INTO country (id, name) VALUES (167, 'Netherlands');
INSERT INTO country (id, name) VALUES (168, 'Norway');
INSERT INTO country (id, name) VALUES (169, 'Nepal');
INSERT INTO country (id, name) VALUES (170, 'Nauru');
INSERT INTO country (id, name) VALUES (171, 'New Zealand');
INSERT INTO country (id, name) VALUES (172, 'Oman');
INSERT INTO country (id, name) VALUES (173, 'Pakistan');
INSERT INTO country (id, name) VALUES (174, 'Panama');
INSERT INTO country (id, name) VALUES (175, 'Pitcairn');
INSERT INTO country (id, name) VALUES (176, 'Peru');
INSERT INTO country (id, name) VALUES (177, 'Philippines');
INSERT INTO country (id, name) VALUES (178, 'Palau');
INSERT INTO country (id, name) VALUES (179, 'Papua New Guinea');
INSERT INTO country (id, name) VALUES (180, 'Poland');
INSERT INTO country (id, name) VALUES (181, 'Puerto Rico');
INSERT INTO country (id, name) VALUES (182, 'Korea, Democratic People''s Republic of');
INSERT INTO country (id, name) VALUES (183, 'Portugal');
INSERT INTO country (id, name) VALUES (184, 'Paraguay');
INSERT INTO country (id, name) VALUES (185, 'Palestine, State of');
INSERT INTO country (id, name) VALUES (186, 'French Polynesia');
INSERT INTO country (id, name) VALUES (187, 'Qatar');
INSERT INTO country (id, name) VALUES (188, 'Réunion');
INSERT INTO country (id, name) VALUES (189, 'Romania');
INSERT INTO country (id, name) VALUES (190, 'Russian Federation');
INSERT INTO country (id, name) VALUES (191, 'Rwanda');
INSERT INTO country (id, name) VALUES (192, 'Saudi Arabia');
INSERT INTO country (id, name) VALUES (193, 'Sudan');
INSERT INTO country (id, name) VALUES (194, 'Senegal');
INSERT INTO country (id, name) VALUES (195, 'Singapore');
INSERT INTO country (id, name) VALUES (196, 'South Georgia and the South Sandwich Islands');
INSERT INTO country (id, name) VALUES (197, 'Saint Helena, Ascension and Tristan da Cunha');
INSERT INTO country (id, name) VALUES (198, 'Svalbard and Jan Mayen');
INSERT INTO country (id, name) VALUES (199, 'Solomon Islands');
INSERT INTO country (id, name) VALUES (200, 'Sierra Leone');
INSERT INTO country (id, name) VALUES (201, 'El Salvador');
INSERT INTO country (id, name) VALUES (202, 'San Marino');
INSERT INTO country (id, name) VALUES (203, 'Somalia');
INSERT INTO country (id, name) VALUES (204, 'Saint Pierre and Miquelon');
INSERT INTO country (id, name) VALUES (205, 'Serbia');
INSERT INTO country (id, name) VALUES (206, 'South Sudan');
INSERT INTO country (id, name) VALUES (207, 'Sao Tome and Principe');
INSERT INTO country (id, name) VALUES (208, 'Suriname');
INSERT INTO country (id, name) VALUES (209, 'Slovakia');
INSERT INTO country (id, name) VALUES (210, 'Slovenia');
INSERT INTO country (id, name) VALUES (211, 'Sweden');
INSERT INTO country (id, name) VALUES (212, 'Eswatini');
INSERT INTO country (id, name) VALUES (213, 'Sint Maarten (Dutch part)');
INSERT INTO country (id, name) VALUES (214, 'Seychelles');
INSERT INTO country (id, name) VALUES (215, 'Syrian Arab Republic');
INSERT INTO country (id, name) VALUES (216, 'Turks and Caicos Islands');
INSERT INTO country (id, name) VALUES (217, 'Chad');
INSERT INTO country (id, name) VALUES (218, 'Togo');
INSERT INTO country (id, name) VALUES (219, 'Thailand');
INSERT INTO country (id, name) VALUES (220, 'Tajikistan');
INSERT INTO country (id, name) VALUES (221, 'Tokelau');
INSERT INTO country (id, name) VALUES (222, 'Turkmenistan');
INSERT INTO country (id, name) VALUES (223, 'Timor-Leste');
INSERT INTO country (id, name) VALUES (224, 'Tonga');
INSERT INTO country (id, name) VALUES (225, 'Trinidad and Tobago');
INSERT INTO country (id, name) VALUES (226, 'Tunisia');
INSERT INTO country (id, name) VALUES (227, 'Turkey');
INSERT INTO country (id, name) VALUES (228, 'Tuvalu');
INSERT INTO country (id, name) VALUES (229, 'Taiwan, Province of China');
INSERT INTO country (id, name) VALUES (230, 'Tanzania, United Republic of');
INSERT INTO country (id, name) VALUES (231, 'Uganda');
INSERT INTO country (id, name) VALUES (232, 'Ukraine');
INSERT INTO country (id, name) VALUES (233, 'United States Minor Outlying Islands');
INSERT INTO country (id, name) VALUES (234, 'Uruguay');
INSERT INTO country (id, name) VALUES (235, 'United States');
INSERT INTO country (id, name) VALUES (236, 'Uzbekistan');
INSERT INTO country (id, name) VALUES (237, 'Holy See (Vatican City State)');
INSERT INTO country (id, name) VALUES (238, 'Saint Vincent and the Grenadines');
INSERT INTO country (id, name) VALUES (239, 'Venezuela, Bolivarian Republic of');
INSERT INTO country (id, name) VALUES (240, 'Virgin Islands, British');
INSERT INTO country (id, name) VALUES (241, 'Virgin Islands, U.S.');
INSERT INTO country (id, name) VALUES (242, 'Viet Nam');
INSERT INTO country (id, name) VALUES (243, 'Vanuatu');
INSERT INTO country (id, name) VALUES (244, 'Wallis and Futuna');
INSERT INTO country (id, name) VALUES (245, 'Samoa');
INSERT INTO country (id, name) VALUES (246, 'Yemen');
INSERT INTO country (id, name) VALUES (247, 'South Africa');
INSERT INTO country (id, name) VALUES (248, 'Zambia');
INSERT INTO country (id, name) VALUES (249, 'Zimbabwe');